var modal;
var charades = [
    "Teddy bear;60",
    "Snowball fight;30",
    "The Olympics;90",
    "Trumpet;30",
    "Basketball;30",
    "Christmas tree;30",
    "Rollercoaster;30",
    "Cheerleader;30",
    "Haircut;30",
    "Shoveling snow;30",
    "Hamster wheel;60",
    "Shaving cream;30",
    "Thomas the Tank Engine;60",
    "Getting a pie in the face;90",
    "Metal detector;30",
    "Speed skating;30",
    "Scoring a goal;60",
    "Polar bear;60",
    "Thunder and lightning;90",
    "North Pole;90",
    "Pilot;30",
    "Policewoman;60",
    "Superman;30",
    "Piggy bank;60",
    "Credit Card;90",
    "Feather Pillow;60",
    "Rock star;30",
    "Flag pole;30",
    "Cross-country skiing;60",
    "Tarzan;60",
    "Sleeping bag;30",
    "First day of school;90",
    "Banging your finger with a hammer;60",
    "Buffet restaurant;90",
    "Wrapping presents;30",
    "Hot-air balloon;60",
    "Treading water;60",
    "Seahorse;60",
    "Mailing a letter;90",
    "Snowboarding;30",
    "Tuna sandwhich;60",
    "Crayons;30",
    "Classical music;90",
    "Skateboarding;30",
    "Zoo keeper;90",
    "Gorilla;30",
    "Plumber;90",
    "Orchestra;90",
    "Church bells;60",
    "Whoopee cushion;60",
    "Kittens;30",
    "Horse jumping;60",
    "Humpback whale;90",
    "Lifeguard;60",
    "Dental floss;60",
    "Answering the phone;30",
    "Baby bottle;30",
    "Spiderman;60",
    "Alarm clock;30",
    "Spaghetti and meatballs;90",
    "Baking a cake;90",
    "Eating a lemon;90",
    "Flashlight;30",
    "Building an igloo;90",
    "Baking cookies;60",
    "Submarine;60",
    "Stained glass window;90",
    "Pirate;60",
    "Beaver;60",
    "Coffee mug;30",
    "Fireworks;60",
    "Compass;30",
    "Rocking chair;30",
    "Garden gnome;90",
    "Valentines day;90",
    "Time machine;90",
    "Alien;60",
    "Scarecrow;30",
    "Throne;60",
    "Three-legged race;90",
    "Crying;30",
    "Cookie jar;60",
    "Setting the table;90",
    "Water slide;60",
    "Monsters under the bed;60",
    "Milk a cow;90",
    "Watering can;60",
    "Singing in the shower;90",
    "Sharing a milkshake;60",
    "Sunglasses;30",
    "Tightrope walker;60",
    "Lion;30",
    "Making your bed;60",
    "Movie night;90",
    "Recycle;90",
    "Parachute;60",
    "Musical chairs;90",
    "Which;30",
    "Playing the piano;30",
    "Beauty Contest;90",
    "Pull a rabbit out of your hat;90",
    "High jumping;60",
    "Turtle;30",
    "Picnic;60",
    "Wizard of Oz;90",
    "Movie star;60",
    "Surfing;60",
    "Balancing on one leg;30",
    "Tell a joke;90",
    "Thirsty;60",
    "Kneading dough;60",
    "Marshmallows;60",
    "Tooth Fairy;60",
    "Playing Cards;60",
    "Messy hair;60",
    "Karate;60",
    "Washing your hair;30",
    "Batman and Robin;90",
    "Soaking in the tub;90",
    "Running late;60",
    "Making a salad;90",
    "Bacon and Eggs;90",
    "Totem pole;60",
    "Hole in one;30",
    "Baseball;30",
    "Little Red Riding Hood;90",
    "Flying a Kite;30",
    "Flipping pancakes;60",
    "Flying saucer;90",
    "Tyrannosaurus Rex;60",
    "King and Queen;90",
    "Pillow Fight;60",
    "Hearing Aid;90",
    "Horseshoe;30",
    "Swatting a fly;60",
    "Crawling baby;60",
    "Three Little Pigs;60",
    "Popsicle;30",
    "Moon;30",
    "The cow jumped over the moon;90",
    "Sent to the principals office;90",
    "Sign language;30",
    "Gym class;90",
    "Sleep walking;60",
    "Licking an ice cream cone;60",
    "Mad scientist;90",
    "Popcorn;30",
    "Snowman;30",
    "Playing tag;60",
    "Checkers;60",
    "Broccoli;60",
    "Pencil sharpener;60",
    "Big Bad Wolf;90",
    "Fireplace;90",
    "Clown;60",
    "Bouncy castle;60",
    "In a time out;90",
    "Building a sand castle;90",
    "Magic potion;90",
    "Playing hide-and-seek;90",
    "Woodpecker;60",
    "Wooden leg;60",
    "Vampire Bat;60",
    "Dentist;60",
    "Penguin;30",
    "Firefighter;60",
    "Cowboy;60",
    "Trapeze artist;30",
    "Freezing to death;30",
    "Rock, paper, scissor;30",
    "Playing drums;30",
    "Krazy Glue;60",
    "Thumb war;30",
    "Fish out of water;60",
    "Windmill;30",
    "Butterfly;30",
    "Climbing wall;60",
    "Helicopter;30",
    "Washing the car;60",
    "Ninja;60",
    "Santa Claus;60",
    "Harry Potter;90",
    "Folding the laundry;90",
    "Monkey bars;30",
    "Climbing a mountain;60",
    "Grating cheese;30",
    "Fish on a hook;60",
    "Bubble bath;30",
    "Panting a mural;60",
    "Building a bridge;90",
    "Exploring a cave;90",
    "School bus;30",
    "Hoola-hoop;30",
    "Measuring tape;30",
    "Carving a turkey;60",
    "Moving a refridgerator;90",
    "Rubik's cube;30",
    "Red light;60",
    "Chalkboard;30",
    "Arranging a banquet;90",
    "Swimming;30",
    "Floating;30",
    "Pumpkin carving;60",
    "Rocket ship;30",
    "Marching band;60",
    "Planting a garden;60",
    "Chicken wings;60",
    "Chef;30",
    "Running shoes;60",
    "Eating with chopsticks;60",
    "Dolphin;60",
    "Jigsaw puzzle;60",
    "Christmas stockings;30",
    "Gingerbread man;60",
    "Backpack;30",
    "Lifting weights;60",
    "Surfing the web;90",
    "Goldfish;90",
    "Librarian;90",
    "Belly dancing;60",
    "Skipping rope;30",
    "Chewing gum;30",
    "Easter eggs;90",
    "Cough medicine;30",
    "Curious George;90",
    "Somersault;30",
    "Walking on stilts;30",
    "Gloves;30",
    "Sundial;60",
    "Running a marathon;60",
    "The Nutcracker;60",
    "Bowling;30",
    "Eating a pizza;90",
    "Figure skating;60",
    "Chicken dance;60",
    "Mouthwash;30",
    "Peanut butter and jelly sandwich;90",
    "Bird Watching;30",
    "Skunk;30",
    "Sumo wrestling;30",
    "Barbecue;30",
    "Frog in your throat;60",
    "Drawing a picture;30",
    "Talking in your sleep;90",
    "Sunset;60",
    "Candy Cane;30",
    "Losing your memory;90",
    "Saxophone;30",
    "Washing machine;60",
    "Finger puppets;60",
    "Remote control;30",
    "Bald Eagle;30",
    "Ballerina;30",
    "Soccer player;30",
    "Listening to music;30",
    "Bedtime story;60",
    "Skyscraper;90",
    "Bagpipes;30",
    "Robin Hood;60",
    "Ferris wheel;60",
    "Choir;60",
    "Feeding the ducks;90",
    "False teeth;60",
    "Hedge clippers;90",
    "Riding a bike;30",
    "Picking flowers;60",
    "Electric guitar;60",
    "Using a Laptop;60",
    "Binoculars;30",
    "Tire swing;60",
    "Doing math;90",
    "Astronaut;60",
    "Big Bird;60",
    "Arrow;30",
    "Reading a book;30",
    "Broom;30",
    "Robot;60",
    "Eating a banana;30",
    "Making noise;90",
    "Blowing bubbles;30",
    "Lighthouse;60",
    "Detective;60",
    "Roller blades;30",
    "Confused;60",
    "Mount Everest;60",
    "Hotdog eating contest;90",
    "Halloween;90",
    "Mowing the lawn;60",
    "Kangaroo;60",
    "Snoring;60",
    "Humpty Dumpty;90",
    "Watching TV;60",
    "Broken nose;30",
    "Dog house;60",
    "Bunk beds;90",
    "Stunt man;90",
    "Throwing a boomerang;60",
    "Taking the train;60",
    "The alphabet;90",
    "Sword fight;30",
    "Magnifying glass;30",
    "Camel;60",
    "Driving;30",
    "Wedding;30",
    "Magic carpet;60",
    "Watching a scary movie;90"
];
$(document).ready(function(){
    loadCharade();
    $('.btn').click(loadCharade);
    
})

function loadCharade(){

    var r = charades[Math.floor(Math.random() * charades.length)].split(';');
    $('.charade').text(r[0]);
    $('.time').text(`${r[1]} Seconds`)
}